# Generated by Django 5.2.7 on 2025-10-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisations associated with this application.",
                related_name="applications",
                to="core.organisation",
            ),
        ),
    ]
